### ISSUE TITLE
Decouple branch states from rule states

### ISSUE THREAD

**Issue by adityasaky** [adityasaky/gittuf#13]
Currently, new valid states for branches (latest trusted commit, for example) is recorded in targets metadata. This issue discusses decoupling the records of branch states from the states that describe the access control policies for a repository. This has a number of advantages:
1. It greatly reduces the footprint of TUF metadata
2. It is simpler to maintain state linearity of the TUF metadata if the state is only tracking changes to access control policies--these are far rarer than commits in practice
3. A separate record of branch states means that it can record states of branches not explicitly protected by the rules (ex: short lived feature branches) but are still vulnerable to branch state attacks
4. (side effect) The CLI would improve as the user would no longer have to specify the role they're updating

**Comment by adityasaky** [comment]
A decoupled state log would very closely resemble what's described in https://www.usenix.org/system/files/conference/usenixsecurity16/sec16_paper_torres-arias.pdf. For every reference, we'd have an entry recording current state and the previous state. Each entry would be signed by the user updating the state log (and this user can be separate from that creating a commit at some reference, merely an observer).

**Comment by adityasaky** [comment]
Decoupling as described in this thread requires a redesign of metadata management. Specifically, the internal only gitstore package will now have:
* `policy-state`, very similar to the current state log but from now only handling policies described as TUF metadata
* `reference-state`, brand new namespace within `refs/gittuf/`, each tracked ref in a copy of the repo has its own entry
* `last-trusted`, very similar to the current version except instead of state IDs pointing to `policy-state`, they point to `reference-state` entries

## reference-state

Stored within `refs/gittuf/reference-state/`, each entry corresponds to a tracked ref. For example, the `main` branch is tracked at `refs/gittuf/reference-state/main`. This file points to a blob artifact corresponding to the reference state log entry. The entry has the following fields:
* `last-entry`: ID of the preceding blob
* `tip`: ID of the tip of the reference
* `signature`: a signature object over the `last-entry` and `tip` fields

Question: should an entry contain a record of the policy state it was created against? This might help detect and reconcile drifts in states.

**Comment by adityasaky** [comment]
Side note: `gitstore` is no longer a lightweight interface to handle interactions to store TUF metadata in the gittuf namespace. We should rename it and clean up the implementation. Perhaps `internal/gittuf-metadata` and `package metadata`?

**Comment by adityasaky** [comment]
I've been doing some thinking about whether we should split the current state log into policy state logs and reference state logs and I have some arguments against doing so. I'm going to summarize them here and keep thinking about this.

Currently, we have a unified state log. Each entry in the state log corresponds to one state which has a set of TUF metadata valid for that state. We use Git itself to maintain this log. As such, each state is identified by a commit ID in the refs/gittuf/ namespace.

A new state is created every time TUF metadata is signed. This can happen when the access control policies are updated (ex: new restrictions) or (currently) when a new commit is created at some branch. Delegated targets metadata is signed that indicates the repository is at a state where the corresponding branch's tip is that new commit. With all actions tracked in a single state tree, it is simple to map each state to the policies that apply to it. A state is valid if the changes to files / refs in the Git repo it records are valid against the policies in its parent state.

By separating the state tree into a tree for policies and another for reference state changes, we lose this clear mapping between an entry and the policies active for it. One option is to have the reference state entry record the state of the policy but an attacker who controls a developer's key used to sign reference state entries can trivially point to incorrect policy states.

Further, one of the reasons we were considering this is to ensure we don't have authorship misattribution when an observer signs a state entry for a commit created by another contributor who does not use gittuf. However, this seems to be unaffected whether the state entry is in the form of TUF metadata or as described in https://github.com/adityasaky/gittuf/issues/13#issuecomment-1365355313. The other benefits such as CLI improvements and the footprint of TUF metadata may be accomplished by making the same kind of assumptions we would with a separate reference state tree. Specifically, the delegation structure can be more opinionated than it currently is. We can map each tracked reference to a separate delegation from the top level targets role and automatically sign new versions for that role when the reference is updated. This is essentially the same structure as a per-reference state tree.

**Comment by adityasaky** [comment]
> Specifically, the delegation structure can be more opinionated than it currently is.

Here are some of my thoughts. I'll update as I test these out.

* All rules / policies over namespaces are defined in the top level targets role. As such, they can all be studied from a single piece of metadata.
* Each reference has a role dedicated to it. This way, each role is a log of what happened to a particular reference. Also, the UX is improved because roles can be inferred.
* Policies in targets.json essentially define who can sign metadata for a particular reference and this is cross-verified with the signatures on that reference's dedicated role.

**Comment by adityasaky** [comment]
Given that we have a very predefined structure with delegations, we can greatly clean up the search-for-correct-metadata bits. We can go straight to the expected role for its entry and we can infer the keys to use to verify that role from top level targets metadata, the delegation that matches the rule. Note that we're deviating by having the role recording for a reference possibly have a different name than the delegation name in top level targets. This is important as one policy (i.e., a delegation) may apply to multiple branches but each branch has its own metadata record. This would also be the case for separated logs.

**Comment by adityasaky** [comment]
## Proposal for Separating State Log from Policy

We've been having some conversations about how we can decouple the reference state log from the namespace that currently tracks policies. Currently, there's a single state log where each state contains a full set of TUF policies as well as entries for each ref tracked by gittuf. After #14, the policies live in targets files and entries for each ref is contained in targets roles named after the ref.

The decoupling would mean, as noted before in this thread, that the reference state log resembles the omitting commits paper more closely. Specifically, this log contains entries when the states of tracked refs change and it compulsorily tracks the namespace containing TUF policies. Each entry in the log contains the hash of its parent, the reference itself, the new commit ID for that reference, and an incremental count of entries. That is, the first entry is 1, the next points to 1 and its count is recorded as 2, and so on. Finally, each entry contains the integer value of the last entry in the log that modified a particular ref. For example, if entries 1, 2, 3 pertain to changes to the TUF namespace, 4, 5 pertain to other namespaces, and 6 again pertains to the TUF namespace, the entry for 6 points to 3 as the last time the TUF namespace was modified. Note that both the number 3 and its hash identifier should be stored to make it easier to look up that entry in Git's content addressed object store.

In this setup, when pulling in changes from a remote, the remote RSL is fetched and the client parses each new entry compared to its local RSL. For all entries corresponding to the ref being pulled, TUF policies are evaluated to ensure that an authorized key was used to sign the RSL entry _and_ that the signing key was authorized to make the changes that were made to files tracked in the repository. Note that when parsing entries in the RSL, the client also incorporates changes made to the TUF namespace to handle updates to policy.

Now, in situations where multiple refs are tracked, the policy state may be updated while validating one ref but another ref may lag behind. Any change made to a ref must be evaluated against the policy active at the time of the change. As such, when stale refs are "catching up", it's important to quickly identify the policy active at the time. In the current setup, as every state also contains its policies, it's trivial. With a decoupled setup as described here, identifying which policy state to use may require expensive operations walking back state entries to find the last change to the TUF namespace. As policies may be less frequently updated, such operations may take longer and longer as repository activity increases. This is where the pointer in each entry to the last entry pertaining to a ref (and the integer value) help. The integer value can be used to quickly check which policy entry to use--the closest entry with a lower count to the state being validated.

**Comment by JustinCappos** [comment]
Does every party pulling the RSL check the policy for all branches (after what they have seen) when they do this?  

If so, I think this is fairly costly, but provides solid protection.  

If not, then you may need to decide how to unwind situations where there was a violation on a branch many commits ago...

**Comment by adityasaky** [comment]
I'll be updating https://github.com/adityasaky/gittuf/blob/main/docs/specification.md with the changes here to get the design ready to go for sanity checks. I'll also include some discussion about recover.

**Comment by adityasaky** [comment]
One of the things that'll happen with the move to traditional RSLs is that entries should be created during `push`, `merge` etc operations rather than `commit`. I'm working to incorporate this into #16.
